### ISSUE TITLE
cmake and autotools create different SONAMEs

### ISSUE THREAD

**Issue by Hello71** [LibVNC/libvncserver#122]
cmake sets SONAME to 0.9.10, which is _not how SONAME works_. autotools is slightly better, setting it to 1.0.0, but it's unclear what ABI change exactly this reflects.

**Comment by bk138** [comment]
Care to create a pull request?

**Comment by Hello71** [comment]
what's it *supposed* to be?

**Comment by bk138** [comment]
0.0.0 as autotools does it. Thanks!

**Comment by bk138** [comment]
Seems 2daa082773c4a4f0481879204b3e3b0361624330 is the culprit...

**Comment by bk138** [comment]
After reading up a bit on the issue, the SONAME should be 
`libvncserver.so.1`
which you can check via
`objdump -p libvncserver.so<whatever number> | grep SONAME`

**Comment by Hello71** [comment]
what ABI change does this reflect?

**Comment by bk138** [comment]
Fixed by 2f54d3ef628e814c52126de026c976048af6dd78

**Comment by Hello71** [comment]
not really fixed, the cmake full library name is still incorrect. `libvncserver.so.1 -> libvncserver.0.9.12` doesn't make any sense

**Comment by bk138** [comment]
What do you think it should be instead?

**Comment by bk138** [comment]
Maybe @cinemast can chime in here...

**Comment by cinemast** [comment]
It is explained here: http://pusling.com/blog/?p=352

If you apply [semantic versioning](http://semver.org/) to your project (which I think you should do, if not already the case), major version and SONAME usually match. If not, they have to be decoupled. 

From my point of view, the above chain `libvncserver.so -> libvncserver.so.1 -> libvncserver.0.9.12 ` makes perfect sense and is as intended.

* The `libvncserver.so` link reflects the default target used by the linker.
* The `libvncserver.so.1` link is used  verify which library version (not SO version) reflects the SONAME API compliance with SONAME version 1.
* The `libvncserver.0.9.12` is the actual library suffixed with its current version.

@Hello71 what is your objection with this here? In what way does it not make any sense?

**Comment by Hello71** [comment]
"didn't make any sense" was probably an overreaction.

it's conventional that the library name begins with the SONAME, although not technically required. it is conventional that if a library does not use standard versioning, then the library name be something like `libfoo.so.1.0.0` or simply `libfoo.so.1`, the same as the SONAME. however, many packages break this convention:

    for f in {/lib,/usr/lib,/usr/local/lib}/*.so.*.*.*; do [[ -f ${f%.*.*} ]] || echo ${f%.*.*.*}*; done | grep '^[^ ]* [^ ]* '

**Comment by Hello71** [comment]
to summarize, the present situation is not perfect in an idealist world, but is probably "good enough".

**Comment by Hello71** [comment]
oh, and my other point was that autotools and cmake are still inconsistent, but as long as the SONAMEs match, I guess it's not too big of an issue.

**Comment by bk138** [comment]
@Hello71 Autotools will eventually be removed for 0.9.12.
